#!/bin/bash
######################################################
#
# Prepend the current branch name to every commit message.
#
# @version 2.2.0
#
# @notice Changed order of message to add task number to
#         body instead of subject.
#
######################################################

source /e/scripts/git/hooks/version-1/prepare-commit-msg
