name: Create GitHub Release
run-name: Create release for ${{ github.ref }} on GitHub.
env:
  VERSION: 2.0.0

on:
  push:
    tags-ignore:
      - "*beta*"

jobs:
  create-release:
    name: Create release for ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref }}
          draft: false
          prerelease: false
          files: Release.txt
