name: Deploy to WordPress.org
env:
  # Can't specify VERSION, or the plugin will deploy in that version.  
  # VERSION: 3.0.0
  NODE_VERSION: '20.11.0'
  PHP_VERSION: '8.3'
  TZ: 'America/New_York'

on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
