name: Plugin asset/readme update

env:
  # Can't specify VERSION, or the plugin will deploy in that version.  
  TZ: 'America/Chicago'
  
on:
  push:
    branches:
      - deploy
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
