name: Plugin asset/readme update
env:
  # Can't specify the VERSION, or the plugin will deploy in that version.  
  # VERSION: 2.0.0
  IGNORE_OTHER_FILES: true
  TZ: 'America/New_York'

on:
  push:
    branches:
      - deploy
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
